"""orgs + calls/segments/audits with org_id NOT NULL (CL-4).

Revision ID: 0001_orgs_calls
Revises:
Create Date: 2026-08-24
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

from backend.org_ids import DEFAULT_ORG_ID

revision: str = "0001_orgs_calls"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        f"""
        CREATE TABLE orgs (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        INSERT INTO orgs (id, name)
        VALUES ('{DEFAULT_ORG_ID}', 'default')
        ON CONFLICT (id) DO NOTHING;

        CREATE TABLE calls (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            org_id UUID NOT NULL REFERENCES orgs (id) ON DELETE RESTRICT,
            audio_url TEXT NOT NULL,
            job_id TEXT,
            status TEXT,
            full_text TEXT,
            speakers INTEGER,
            audio_seconds DOUBLE PRECISION,
            raw_json TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            pyai_call_id TEXT,
            filename TEXT,
            source TEXT,
            external_id TEXT,
            UNIQUE (org_id, audio_url)
        );

        CREATE TABLE segments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            org_id UUID NOT NULL REFERENCES orgs (id) ON DELETE RESTRICT,
            call_id BIGINT NOT NULL REFERENCES calls (id) ON DELETE CASCADE,
            seq INTEGER,
            speaker TEXT,
            channel INTEGER,
            "start" DOUBLE PRECISION,
            "end" DOUBLE PRECISION,
            text TEXT
        );

        CREATE TABLE audits (
            call_id BIGINT PRIMARY KEY REFERENCES calls (id) ON DELETE CASCADE,
            org_id UUID NOT NULL REFERENCES orgs (id) ON DELETE RESTRICT,
            audit_json TEXT,
            rubric_hash TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX idx_calls_org_id ON calls (org_id);
        CREATE INDEX idx_segments_org_id ON segments (org_id);
        CREATE INDEX idx_audits_org_id ON audits (org_id);
        CREATE INDEX idx_segments_call_id ON segments (call_id);

        CREATE UNIQUE INDEX idx_calls_org_source_external
            ON calls (org_id, source, external_id)
            WHERE source IS NOT NULL AND external_id IS NOT NULL;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP INDEX IF EXISTS idx_calls_org_source_external;
        DROP INDEX IF EXISTS idx_segments_call_id;
        DROP INDEX IF EXISTS idx_audits_org_id;
        DROP INDEX IF EXISTS idx_segments_org_id;
        DROP INDEX IF EXISTS idx_calls_org_id;
        DROP TABLE IF EXISTS audits;
        DROP TABLE IF EXISTS segments;
        DROP TABLE IF EXISTS calls;
        DROP TABLE IF EXISTS orgs;
        """
    )
