"""api_usage with org_id (CL-5; matches SQLite usage table).

Revision ID: 0002_api_usage
Revises: 0001_orgs_calls
Create Date: 2026-08-24
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0002_api_usage"
down_revision: Union[str, Sequence[str], None] = "0001_orgs_calls"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE api_usage (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            org_id UUID NOT NULL REFERENCES orgs (id) ON DELETE RESTRICT,
            provider TEXT NOT NULL,
            method TEXT NOT NULL,
            path TEXT NOT NULL,
            status INTEGER,
            units DOUBLE PRECISION,
            units_raw TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX idx_api_usage_org_id ON api_usage (org_id);
        CREATE INDEX idx_api_usage_created ON api_usage (created_at);
        CREATE INDEX idx_api_usage_provider ON api_usage (provider, created_at);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP INDEX IF EXISTS idx_api_usage_provider;
        DROP INDEX IF EXISTS idx_api_usage_created;
        DROP INDEX IF EXISTS idx_api_usage_org_id;
        DROP TABLE IF EXISTS api_usage;
        """
    )
